import logging

from src.agents.base import BaseAgent
from src.models.agent_output import ChairmanOutput, Vote
from src.models.state import ICState

logger = logging.getLogger(__name__)

# Minimum number of votes required for a valid decision.
QUORUM = 3


class ChairmanAgent(BaseAgent):
    """
    Supervisor node — runs after all parallel agents complete.
    Aggregates votes, checks quorum, and issues the final IC decision.
    Vote tallying is deterministic (no LLM); rationale narrative wired in Phase 4.
    """

    agent_id = "chairman"

    def run(self, state: ICState) -> dict:
        vote_tally = self._collect_votes(state)
        final_decision = self._tally(vote_tally)
        quorum_met = len(vote_tally) >= QUORUM

        output = ChairmanOutput(
            final_decision=final_decision,
            vote_tally={k: v.value for k, v in vote_tally.items()},
            quorum_met=quorum_met,
            resolution_rationale=(
                "[placeholder] Chairman's resolution narrative "
                "will be generated by LLM in Phase 4."
            ),
            conditions=(
                ["[placeholder] Define conditions before approval"]
                if final_decision == Vote.CONDITIONAL
                else []
            ),
        )
        return {
            "chairman_output": output,
            "stage_log": [f"chairman: decision={final_decision.value}"],
        }

    # ── Helpers ───────────────────────────────────────────────────────────────

    @staticmethod
    def _collect_votes(state: ICState) -> dict[str, Vote]:
        """Pull votes from all agent outputs present in state."""
        mapping = {
            "financial_analysis": state.get("financial_output"),
            "risk": state.get("risk_output"),
            "bull": state.get("bull_output"),
            "bear": state.get("bear_output"),
        }
        return {
            agent_id: output.vote
            for agent_id, output in mapping.items()
            if output is not None
        }

    @staticmethod
    def _tally(votes: dict[str, Vote]) -> Vote:
        """
        Pure deterministic vote aggregation — no LLM involved.
        Majority wins; CONDITIONAL beats REJECT when tied.
        """
        counts = {v: 0 for v in Vote}
        for v in votes.values():
            counts[v] += 1

        if counts[Vote.APPROVE] > counts[Vote.REJECT]:
            return Vote.APPROVE
        if counts[Vote.REJECT] > counts[Vote.APPROVE]:
            return Vote.REJECT
        return Vote.CONDITIONAL  # tie-breaker
